import { Toaster } from "@/components/ui/toaster";
import SessionProvider from "./SessionProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <section className="flex flex-col justify-between h-screen">
            <main className="mb-auto flex-1">{children}</main>
          </section>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
